CREATE TABLE [dbo].[Comment]
(
	[Id] INT NOT NULL PRIMARY KEY IdENTITY,
	[Issue] UNIQUEIDENTIFIER NOT NULL,
	[IssueType] INT NOT NULL,
	[User] VARCHAR(36) NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	CONSTRAINT FK_User_Comment FOREIGN KEY ([User]) REFERENCES [CollabileUser] (Id)
)
