CREATE TABLE [dbo].[Release]
(
	[Id] INT NOT NULL PRIMARY KEY IdENTITY,
	[Index] INT NOT NULL,
    [Name] NVARCHAR(50) NOT NULL,
	[StartDate] DATETIME2 NOT NULL,
	[EndDate] DATETIME2 NOT NULL,
	[Project] NVARCHAR(20) NOT NULL,
	CONSTRAINT FK_Project_Release FOREIGN KEY ([Project]) REFERENCES [Project] ([Key])
)
