CREATE TABLE [dbo].[WorkLog]
(
	[Id] INT NOT NULL PRIMARY KEY IdENTITY,
	[Task] UNIQUEIDENTIFIER NOT NULL,
	[User] VARCHAR(36) NOT NULL,
	[Effort] DECIMAL NOT NULL,
	[StartDate] DATETIME2 NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	CONSTRAINT FK_Task_WorkLog FOREIGN KEY ([Task]) REFERENCES [Task] ([Id]),
	CONSTRAINT FK_User_WorkLog FOREIGN KEY ([User]) REFERENCES [CollabileUser] (Id)
)
