CREATE TABLE [dbo].[Comment]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Issue] INT NOT NULL,
	[IssueType] INT NOT NULL,
	[User] INT NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	CONSTRAINT FK_User_Comment FOREIGN KEY ([User]) REFERENCES [User] (ID)
)
