CREATE TABLE [dbo].[Team]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [Name] NVARCHAR(50) NOT NULL UNIQUE,
	[Owner] INT NOT NULL,
	CONSTRAINT FK_User_Team_Owner FOREIGN KEY ([Owner]) REFERENCES [User] (ID)
)
